version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
        - sql
    ports:
        - "8081:80"

  mvc:
    image: ${DOCKER_REGISTRY-}mvc
    build:
      context: .
      dockerfile: mvc/Dockerfile
    depends_on:
        - api
    ports:
        - "8080:80"

  sql:
    image: customdbimg:latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Password1"
    ports:
        - "1433:1433"

  redis:
     image: redis

